version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./logs/nginx/:/var/log/nginx/
  backend-blue:
    image: devrank/backend-api:latest
    container_name: backend-blue
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./logs/nest/:/logs/
    expose:
      - 3001
    depends_on:
      - redis
  backend-green:
    image: devrank/backend-api:latest
    container_name: backend-green
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./logs/nest/:/logs/
    expose:
      - 3001
    depends_on:
      - redis
  redis:
    image: redis:6.2.5
    command: redis-server
    volumes:
      - /usr/local/redis/data:/data
    ports:
      - 6379:6379
  frontend-blue:
    image: devrank/frontend:latest
    container_name: frontend-blue
    restart: always
    expose:
      - 8080
  frontend-green:
    image: devrank/frontend:latest
    container_name: frontend-green
    restart: always
    expose:
      - 8080