name: deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
        cache-dependency-path: 'backend/yarn.lock'
    - name: extract version
      run: |
        VERSION=$(grep -o -E "v[0-9]+\.[0-9]+\.[0-9]+" <<< "${{ github.event.head_commit.message }}")
    - name: create Github release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: |
        cd backend
        docker build -t devrank/backend-api:latest -f Dockerfile . --platform linux/x86_64
        docker push devrank/backend-api:latest
        docker tag devrank/backend-api:latest devrank/backend-api:${{ env.VERSION }}
        docker push devrank/backend-api:${{ env.VERSION }}
    - run: |
        cd frontend
        echo "NODE_ENV=production" >> .env.production
        echo "NEXT_PUBLIC_GITHUB_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GITHUB_CLIENT_ID }}" >> .env.production
        echo "NEXT_PUBLIC_GITHUB_SECRET_ID=${{ secrets.NEXT_PUBLIC_GITHUB_SECRET_ID }}" >> .env.production
        echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env.production
        yarn deploy:prod
